// 新戰爭：萬符必應破戒／神代魔術／透化／道具作成 都真的有效
const vm=require('vm'),fs=require('fs');const c={console,Math,JSON};vm.createContext(c);
for(const f of ['Seed_Codex.gs','War_Engine.gs'])vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../../gas/')+f,'utf8'),c);
const E=s=>vm.runInContext(s,c);
const ok=(v,m)=>console.log((v?'✅ ':'❌ ')+m);
E(`var seed=function(id){return SEED_SERVANTS.filter(function(s){return s.id===id})[0]};
var med=warUnit_(seed('美狄亞-Caster')), sab=warUnit_(seed('阿爾托莉雅-Saber')), koj=warUnit_(seed('佐佐木小次郎-Assassin'));
var st={rs:7,master:{hp:100,mhp:100},sv:med,enemies:[],stats:{}};`);
ok(E("warMul_(sab,'dmgTaken',med)")===0.85, '神代魔術：Saber 的對魔力對美狄亞只剩一半（0.7→0.85）');
ok(E("warMul_(sab,'dmgTaken',koj)")===1, '對魔力只擋 Caster：小次郎不受影響');
ok(E("warMul_(koj,'hitTaken',sab)")<1, '透化：小次郎較不易被擊中');
ok(E("warMul_(med,'hitTaken',sab)")<1, '道具作成：美狄亞身前有使魔擋著');
E(`var ev=[];var X={u:med,act:'np',side:'me'},Y={u:sab,act:'attack',side:'a'};sab.hp=sab.mhp;warStrike_(st,X,Y,ev);`);
ok(E("sab.broken===true && warSkRows_(sab).length===0"), '萬符必應破戒：寶具命中後 Saber 這場戰鬥技能全失');
ok(E("ev.some(function(e){return /破除/.test(e.txt)})"), '畫面上有一句說明');
E(`st.enemies=[sab];sab.id='x';sab.alive=true;sab.intel=0;sab.arrive=1;st.engaged=[];st.day=2;st.phase='night';warStartBattle_(st,sab,'sortie',[]);`);
ok(E("!sab.broken && warSkRows_(sab).length>0"), '下一場戰鬥技能回來');
E("koj.broken=false;med.broken=false");
ok(E("warSkRows_(koj).length")>0, '沒被破戒的照常');
E(`var gil=warUnit_(seed('吉爾伽美什-Archer'));gil.id='g';gil.alive=true;gil.intel=2;gil.arrive=1;st.enemies=[gil];st.met=[];
var e1=[],e2=[];warStartBattle_(st,gil,'sortie',e1);st.engaged=[];warStartBattle_(st,gil,'sortie',e2);`);
ok(E("e1.some(function(e){return e.k==='meet'}) && !e2.some(function(e){return e.k==='meet'})"), '敵人的開場那句只在第一次交手說（隔夜再遇不重播）');
E("delete st.met");
ok(E("(function(){var e3=[];st.engaged=[];warStartBattle_(st,gil,'sortie',e3);return e3.some(function(e){return e.k==='meet'})})()"), '舊存檔沒有 met 也不炸，當作沒見過');
