// 🕯️ 第四次的開場假死：百貌哈桑一開戰就「退場」，畫面、目標、敵數都照死了算；它第一次真的出手才露餡。
const S=require('../war_sim.js'); const c=S.ctx, E=S.E;
let ok=0,bad=0; const t=(cond,l,x)=>{ if(cond){ok++;console.log('   ✅ '+l);} else {bad++;console.log('   ❌ '+l+(x!==undefined?'  '+String(x).slice(0,200):''));} };
const seeds={}; E('SEED_SERVANTS').forEach(s=>seeds[s.id]=s); const mn={}; E('SEED_MASTERS').forEach(m=>mn[m.id]=m.name);
const saber=E('SEED_SERVANTS').filter(s=>s.id==='阿爾托莉雅-Saber');
const mk=(war,pl)=>c.warNewGame_({pool:pl||saber,roster:E(war==='4th'?'FATE_4TH_ROSTER':'FATE_5TH_ROSTER'),seeds,masterNames:mn,name:'測',sex:'男',war,seed:5});
let st=mk('4th'); const r0=c.warAct_(st,{t:'start'}); const r={ev:[]}; st.phase='night'; c.warMorning_(st,r.ev);
t(!r0.ev.some(x=>/遠坂邸/.test(x.txt)),'第一天白天還沒發生（那是第一夜的事）');
const h=st.enemies.find(e=>e.hero==='百貌哈桑-Assassin');
t(h&&h.fake&&h.alive,'第二天早報後：哈桑其實活著、標成假死');
t(r.ev.some(x=>/遠坂邸/.test(x.txt)&&/退場/.test(x.txt)),'第二天早報才有原作那段死訊',JSON.stringify(r.ev.map(x=>x.txt)));
const v=c.warView_(st), card=v.foes.find(f=>f.id===h.id);
t(card&&card.alive===false&&!card.hp,'畫面上照「已退場」顯示',JSON.stringify(card));
t(v.alive===c.warAliveCount_(st)-1,'畫面的敵數不算它（勝負還是算）',v.alive+' vs '+c.warAliveCount_(st));
t(!c.warKnownFoes_(st).some(e=>e.id===h.id),'不能把它當突襲目標');
st.phase='night'; const ev=[]; c.warStartBattle_(st,h,'defend',ev);
t(!h.fake&&ev.some(x=>/沒有退場/.test(x.txt)),'第一次真的交手就露餡',JSON.stringify(ev.map(x=>x.txt)));
st=mk('4th'); c.warAct_(st,{t:'start'}); st.phase='night'; c.warMorning_(st,[]); const h2=st.enemies.find(e=>e.hero==='百貌哈桑-Assassin'), o=st.enemies.find(e=>e!==h2&&e.alive); const ev2=[];
c.warAutoBattle_(st,h2,o,ev2); t(!h2.fake&&ev2.some(x=>/沒有退場/.test(x.txt)),'跟別的從者打起來也會露餡（早報）');
const s1=mk('4th'); c.warAct_(s1,{t:'start'}); const h1=s1.enemies.find(e=>e.hero==='百貌哈桑-Assassin');
t(!h1.fake&&c.warView_(s1).alive===c.warAliveCount_(s1),'第一天：還是普通的未知敵人，敵數照算');
s1.met=[h1.id]; s1.phase='night'; const evm=[]; c.warMorning_(s1,evm);
t(!h1.fake&&!evm.some(x=>/遠坂邸/.test(x.txt)),'第一夜就跟它交過手：假死那場戲跳過');
const s5=mk('5th'); t(!s5.enemies.some(e=>e.fake),'第五次沒有這回事');
console.log('── 原作事件表');
const emiya=E('SEED_SERVANTS').filter(s=>s.id==='EMIYA-Archer');
const run=(war,days)=>{ const st=mk(war,emiya); c.warAct_(st,{t:'start'}); const out=[]; for(let d=0;d<days;d++){ const ev=[]; st.phase='night'; st.battle=null; c.warMorning_(st,ev); out.push(...ev.map(x=>x.txt)); } return {st,out}; };
let R=run('5th',3); const hb=R.st.enemies.find(e=>e.hero==='赫拉克勒斯-Berserker');
t(R.out.some(x=>/白髮的少女/.test(x))&&hb.intel>=1,'第五次第 2 天：坡道上的伊莉雅（看穿職階與據點）',JSON.stringify(R.out));
R=run('4th',8); const isk=R.st.enemies.find(e=>e.hero==='伊斯坎達爾-Rider'), dl=R.st.enemies.find(e=>e.hero==='迪盧木多-Lancer');
t(R.out.some(x=>/倉庫街/.test(x))&&isk.intel===2,'第四次第 2 天：倉庫街，征服王自報真名（直接看穿）');
t(R.out.some(x=>/海特飯店/.test(x))&&dl.loc==='廢棄工廠','第 5 天：飯店被炸，迪盧木多搬到廢棄工廠');
R=run('4th',11); const gd=R.st.enemies.find(e=>e.hero==='吉爾德萊-Caster'), la=R.st.enemies.find(e=>e.hero==='蘭斯洛特-Berserker');
t(R.out.some(x=>/黑霧般的騎士/.test(x))&&la.intel>=1,'第四次第 3 天：黑騎士接住金色英靈的寶具擲回去');
t(R.out.some(x=>/海魔/.test(x))&&gd.intel===2&&gd.loc==='未遠川','第四次第 10 天：未遠川的海魔，吉爾德萊真名曝光、據點移到河上',JSON.stringify({i:gd.intel,l:gd.loc}));
R=run('5th',6); const md=R.st.enemies.find(e=>e.hero==='美狄亞-Caster');
t(R.out.some(x=>/集體昏睡/.test(x))&&md.intel>=1,'第五次第 5 天：新都集體昏睡，線頭通往柳洞寺');
const st4=mk('4th',emiya); c.warAct_(st4,{t:'start'}); st4.enemies.find(e=>e.hero==='伊斯坎達爾-Rider').alive=false; const ev4=[]; st4.day=1; st4.phase='night'; c.warMorning_(st4,ev4);
t(!ev4.some(x=>/倉庫街/.test(x.txt)),'涉及的從者已經倒下 → 那條事件整條跳過');
const allHeroes=new Set(E('SEED_SERVANTS').map(s=>s.id)); const evs=E('WAR_CANON_EVENTS_');
t(evs.every(v=>(v.need||[]).concat(Object.keys(v.reveal||{}),Object.keys(v.move||{})).every(h=>allHeroes.has(h))),'事件表點名的從者都存在（改名會叫）');
console.log(bad?('\n❌ '+bad+' 條沒過（通過 '+ok+'）'):('\n✅ 全部 '+ok+' 條通過')); process.exit(bad?1:0);
