// ==========================================
// 🔵 Seed_Codex.gs — 英靈殿(從者範本) + 御主殿 名冊種子（逐字移植自 FATE）
// seedFateCodex_(ss)：英靈殿/御主殿 為空時自動灌入；ensureFateSheets_ 末尾呼叫。
// ==========================================

var SEED_SERVANTS = [
  // 第五次
  { id:'阿爾托莉雅-Saber', cls:'Saber', realName:'阿爾托莉雅·潘德拉貢', wars:['4th','5th'], gender:'女',
    six:{筋力:'B',耐久:'B',敏捷:'B',魔力:'A',幸運:'A',寶具:'A+'},
    classSkills:[{n:'對魔力',r:'B',fx:'nullify_magic'},{n:'騎乘',r:'B',fx:'ride'}],
    skills:[{n:'直感',r:'A',fx:'first_strike'},{n:'魔力放出',r:'A',fx:'burst'},{n:'卡里斯瑪',r:'B',fx:'morale'},
            {n:'風王鐵鎚',r:'A',fx:'wind_strike'}],
    traits:[{n:'王'},{n:'人類'}], np:'誓約勝利之劍（對城 A++）',
    align:'秩序・善', persona:{firstP:'我',words:'騎士道・榮譽・責任',toMaster:'盡忠職守，初期略有距離'} },
  { id:'EMIYA-Archer', cls:'Archer', realName:'無名（EMIYA）', wars:['5th'], gender:'男',
    six:{筋力:'D',耐久:'C',敏捷:'C',魔力:'B',幸運:'E',寶具:'B'},
    classSkills:[{n:'對魔力',r:'D',fx:'nullify_magic'},{n:'單獨行動',r:'B',fx:'solo'}],
    skills:[{n:'心眼(真)',r:'A',fx:'analyze'},{n:'千里眼',r:'C',fx:'aim'},{n:'投影魔術',r:'',fx:'projection'},{n:'無限劍製',r:'',fx:'ubw'}],
    traits:[{n:'人類'}], np:'無限劍製（固有結界）',
    align:'中立・中庸', persona:{firstP:'我',words:'現實・諷刺・隱藏的理想',toMaster:'嘴上不饒人，暗中守護'} },
  { id:'庫丘林-Lancer', cls:'Lancer', realName:'庫·丘林', wars:['5th'], gender:'男',
    six:{筋力:'B',耐久:'C',敏捷:'A',魔力:'C',幸運:'E',寶具:'B'},
    classSkills:[{n:'對魔力',r:'C',fx:'nullify_magic'}],
    skills:[{n:'避矢加護',r:'B',fx:'evade_ranged'},{n:'戰鬥續行',r:'A',fx:'survive'},{n:'刺穿死亡之棘',r:'B',fx:'gae_bolg'}],
    traits:[{n:'神性',r:'低'}], np:'刺穿死棘之槍（對人 B・因果逆轉必中）',
    align:'秩序・中庸', persona:{firstP:'俺',words:'戰士・痛快・重義',toMaster:'爽快直率，討厭被當棋子'} },
  { id:'美杜莎-Rider', cls:'Rider', realName:'美杜莎', wars:['5th'], gender:'女',
    six:{筋力:'C',耐久:'C',敏捷:'A',魔力:'B',幸運:'D',寶具:'A+'},
    classSkills:[{n:'對魔力',r:'B',fx:'nullify_magic'},{n:'騎乘',r:'A+',fx:'ride'}],
    skills:[{n:'怪力',r:'B',fx:'str_up'},{n:'女神的神核',r:'',fx:'divine_core'},{n:'魔眼',r:'A',fx:'petrify'}],
    traits:[{n:'神性'},{n:'女神'}], np:'他人的神殿／駿馬天翔（A+）',
    align:'混沌・善', persona:{firstP:'我',words:'忠誠・守護・自卑',toMaster:'寡言而深情，極度護主'} },
  { id:'美狄亞-Caster', cls:'Caster', realName:'美狄亞', wars:['5th'], gender:'女',
    six:{筋力:'E',耐久:'D',敏捷:'C',魔力:'A',幸運:'B',寶具:'C'},
    classSkills:[{n:'陣地作成',r:'A',fx:'territory'},{n:'道具作成',r:'A',fx:'crafting'}],
    skills:[{n:'高速神言',r:'A',fx:'fast_cast'},{n:'神代魔術',r:'A',fx:'divine_age'},{n:'破戒全咒',r:'C',fx:'rule_breaker'}],
    traits:[{n:'人類'}], np:'破戒全咒（規則破壞者 C）',
    align:'中立・惡', persona:{firstP:'我',words:'背叛的傷痕・渴望被信任',toMaster:'防備但渴望真心相待'} },
  { id:'佐佐木小次郎-Assassin', cls:'Assassin', realName:'佐佐木小次郎', wars:['5th'], gender:'男',
    six:{筋力:'C',耐久:'D',敏捷:'A',魔力:'E',幸運:'E',寶具:'E'},
    classSkills:[{n:'氣息遮斷',r:'D',fx:'stealth'}],
    skills:[{n:'心眼（偽）',r:'A',fx:'analyze'},{n:'透化',r:'B+',fx:'clear_mind'},
            {n:'宗和的心得',r:'B',fx:'unreadable'},{n:'秘劍・燕返',r:'-',fx:'tsubame'}],
    traits:[{n:'人類'}], np:'燕返（對人魔劍・次元摺疊・三段同時斬）',
    align:'中立・中庸', persona:{firstP:'拙者',words:'劍士・閒適・宿命',toMaster:'隨遇而安，只求一戰'} },
  { id:'赫拉克勒斯-Berserker', cls:'Berserker', realName:'赫拉克勒斯', wars:['5th'], gender:'男',
    six:{筋力:'A',耐久:'A',敏捷:'A',魔力:'B',幸運:'C',寶具:'B'},
    classSkills:[{n:'狂化',r:'B',fx:'mad'},{n:'對魔力',r:'?',fx:'nullify_magic'}],
    skills:[{n:'勇猛',r:'A',fx:'morale'},{n:'戰鬥續行',r:'A',fx:'survive'},{n:'十二試煉',r:'A',fx:'god_hand'}],
    traits:[{n:'神性',r:'A'},{n:'王'}], np:'十二試煉（God Hand A）',
    align:'混沌・狂', persona:{firstP:'（狂化）',words:'戰神・守護的殘響',toMaster:'理智被吞沒，僅存護主本能'} },
  // 第四次
  { id:'吉爾伽美什-Archer', cls:'Archer', realName:'吉爾伽美什', wars:['4th','fake'], gender:'男',
    six:{筋力:'B',耐久:'C',敏捷:'C',魔力:'B',幸運:'A',寶具:'EX'},
    classSkills:[{n:'對魔力',r:'E',fx:'nullify_magic'},{n:'單獨行動',r:'A+',fx:'solo'}],
    skills:[{n:'黃金律',r:'A',fx:'wealth'},{n:'卡里斯瑪',r:'A',fx:'morale'},{n:'神性',r:'B',fx:'divine'},
            {n:'王之財寶',r:'A',fx:'gob'},{n:'天之鎖',r:'B',fx:'chain'}],
    traits:[{n:'神性'},{n:'王'}], np:'王之財寶 Gate of Babylon（對人 E~A++）',
    align:'混沌・善', persona:{firstP:'吾',words:'傲慢・王・俯視眾生',toMaster:'視為雜種，幾乎不從令'} },
  { id:'迪盧木多-Lancer', cls:'Lancer', realName:'迪盧木多·奧迪那', wars:['4th'], gender:'男',
    six:{筋力:'B',耐久:'C',敏捷:'A',魔力:'C',幸運:'E',寶具:'C'},
    classSkills:[{n:'對魔力',r:'C',fx:'nullify_magic'}],
    skills:[{n:'戰鬥續行',r:'A',fx:'survive'},{n:'愛之痣',r:'-',fx:'morale'},
            {n:'破魔紅薔薇／必滅黃薔薇',r:'B',fx:'anti_magic_lance'}],
    traits:[{n:'人類'}], np:'破魔紅薔薇 Gáe Dearg・必滅黃薔薇 Gáe Buidhe（雙槍・破魔／不癒之傷）',
    align:'秩序・善', persona:{firstP:'我',words:'忠義・騎士・哀愁',toMaster:'絕對忠誠'} },
  { id:'伊斯坎達爾-Rider', cls:'Rider', realName:'伊斯坎達爾（征服王）', wars:['4th'], gender:'男',
    six:{筋力:'A+',耐久:'A',敏捷:'B',魔力:'C',幸運:'A+',寶具:'A++'},
    classSkills:[{n:'對魔力',r:'D',fx:'nullify_magic'},{n:'騎乘',r:'A+',fx:'ride'}],
    skills:[{n:'卡里斯瑪',r:'B',fx:'morale'},{n:'軍略',r:'B',fx:'tactics'}],
    traits:[{n:'王'}], np:'王之軍勢 Ionioi Hetairoi（對軍 EX）',
    align:'中立・善', persona:{firstP:'余',words:'豪邁・征服・雅量',toMaster:'視為臣下亦為摯友'} },
  { id:'吉爾德萊-Caster', cls:'Caster', realName:'吉爾·德·萊斯（青鬍子）', wars:['4th'], gender:'男',
    six:{筋力:'E',耐久:'E',敏捷:'D',魔力:'C',幸運:'E',寶具:'C'},
    classSkills:[{n:'陣地作成',r:'C',fx:'territory'},{n:'道具作成',r:'C',fx:'crafting'}],
    skills:[{n:'精神汙染',r:'A',fx:'mad'},{n:'螺湮城教本',r:'',fx:'summon_horror'}],
    traits:[{n:'人類'}], np:'螺湮城教本（深淵召喚・召喚大海怪）',
    align:'混沌・惡', persona:{firstP:'我',words:'瘋狂・虔誠扭曲',toMaster:'視龍之介為摯友'} },
  { id:'百貌哈桑-Assassin', cls:'Assassin', realName:'哈桑·薩巴赫（百貌）', wars:['4th'], gender:'男',
    six:{筋力:'C',耐久:'D',敏捷:'B',魔力:'D',幸運:'E',寶具:'D'},
    classSkills:[{n:'氣息遮斷',r:'A+',fx:'stealth'}],
    skills:[{n:'自我改造',r:'B',fx:'self_mod'},{n:'妄想心音',r:'',fx:'zabaniya'}],
    traits:[{n:'人類'}], np:'妄想心音 Zabaniya（心臟摘取）',
    align:'秩序・惡', persona:{firstP:'我們',words:'群體・狂信・無數人格',toMaster:'服從'} },
  { id:'蘭斯洛特-Berserker', cls:'Berserker', realName:'蘭斯洛特（湖之騎士）', wars:['4th'], gender:'男',
    six:{筋力:'A',耐久:'A',敏捷:'A+',魔力:'B',幸運:'C',寶具:'A'},
    classSkills:[{n:'狂化',r:'B',fx:'mad'},{n:'騎乘',r:'A',fx:'ride'},{n:'對魔力',r:'E',fx:'nullify_magic'}],
    skills:[{n:'無窮的鍛鍊',r:'A+',fx:'clear_mind'},{n:'無此花的湖光',r:'A',fx:'weapon_steal'}],
    traits:[{n:'騎士'}], np:'騎士不為孤軍 Knight of Owner（萬物化為兵裝）',
    align:'混沌・狂', persona:{firstP:'（狂化）',words:'悔恨・無言的瘋狂',toMaster:'不語'} },
  // FAKE 樣本
  { id:'恩奇都-Lancer', cls:'Lancer', realName:'恩奇都', wars:['fake'], gender:'無',
    six:{筋力:'B',耐久:'A',敏捷:'A',魔力:'A',幸運:'-',寶具:'A+'},
    classSkills:[{n:'對魔力',r:'?',fx:'nullify_magic'}],
    skills:[{n:'變生',r:'',fx:'shapeshift'},{n:'神性',r:'?',fx:'divine'}],
    traits:[{n:'神性'},{n:'神造兵器'}], np:'天地乖離開闢之星（變化）',
    align:'中立・中庸', persona:{firstP:'我',words:'純真・神造・追尋摯友',toMaster:'溫和而疏離'} },
  { id:'漢斯-Watcher', cls:'Watcher', realName:'漢斯·克里斯汀·安徒生', wars:['fake'], gender:'男',
    six:{筋力:'E',耐久:'E',敏捷:'D',魔力:'C',幸運:'B',寶具:'C'},
    classSkills:[{n:'單獨行動',r:'B',fx:'solo'}],
    skills:[{n:'心眼（真）',r:'B',fx:'analyze'},{n:'故事創作',r:'A',fx:'narrative'},{n:'透化',r:'C',fx:'clear_mind'}],
    traits:[{n:'人類'}], np:'無謬之書／人魚靈藥（輔助）',
    align:'中立・善', persona:{firstP:'我',words:'毒舌・觀察者・童話',toMaster:'冷眼旁觀卻心軟'} },
  // 斯卡哈 三職階
  { id:'斯卡哈-Lancer', cls:'Lancer', realName:'斯卡哈', wars:['客串'], gender:'女',
    six:{筋力:'B',耐久:'A',敏捷:'A',魔力:'B',幸運:'E',寶具:'A'},
    classSkills:[{n:'對魔力',r:'C',fx:'nullify_magic'}],
    skills:[{n:'神速',r:'A',fx:'first_strike'},{n:'戰鬥續行',r:'A',fx:'survive'},
            {n:'原初符文',r:'A',fx:'rune'},{n:'刺穿死亡之棘',r:'A',fx:'gae_bolg'}],
    traits:[{n:'神性'},{n:'人類'}], np:'刺穿死亡之棘景 Gáe Bolg Alternative（對界 A）',
    align:'中立・中庸', persona:{firstP:'我',words:'影之國女王・冷峻嚴師・武人',toMaster:'嚴厲考校，唯認可強者'} },
  { id:'斯卡哈-Assassin', cls:'Assassin', realName:'斯卡哈', wars:['客串'], gender:'女',
    six:{筋力:'C',耐久:'C',敏捷:'A+',魔力:'B',幸運:'D',寶具:'B'},
    classSkills:[{n:'氣息遮斷',r:'B',fx:'stealth'}],
    skills:[{n:'心眼(真)',r:'B',fx:'analyze'},{n:'戰鬥續行',r:'A',fx:'survive'},{n:'原初符文',r:'B',fx:'rune'}],
    traits:[{n:'神性'},{n:'人類'}], np:'豺狼的胃袋（影縫穿刺 B）',
    align:'中立・中庸', persona:{firstP:'我',words:'潛行的女王・冷冽・致命',toMaster:'冷眼試探、出手無情'} },
  { id:'斯卡哈-Caster', cls:'Caster', realName:'斯卡哈·斯卡薩哈（Skadi）', wars:['客串'], gender:'女',
    six:{筋力:'E',耐久:'D',敏捷:'C',魔力:'A',幸運:'B',寶具:'A'},
    classSkills:[{n:'陣地作成',r:'A',fx:'territory'},{n:'高速神言',r:'A',fx:'fast_cast'}],
    skills:[{n:'原初符文',r:'EX',fx:'rune'},{n:'女神的神核',r:'',fx:'divine_core'},{n:'神代魔術',r:'A',fx:'divine_age'}],
    traits:[{n:'神性'},{n:'女神'}], np:'彼岸薔薇之園・原初的符紋（對界 A）',
    align:'中立・善', persona:{firstP:'吾',words:'北歐女神・溫柔而威嚴・守護者',toMaster:'溫柔包容、暗藏神威'} },
  // strange Fake
  { id:'理查一世-Saber', cls:'Saber', realName:'獅心王・理查一世', wars:['fake'], gender:'男',
    six:{筋力:'B',耐久:'B',敏捷:'C',魔力:'C',幸運:'A',寶具:'B'},
    classSkills:[{n:'對魔力',r:'B',fx:'nullify_magic'},{n:'騎乘',r:'A',fx:'ride'}],
    skills:[{n:'卡里斯瑪',r:'B',fx:'morale'},{n:'軍略',r:'B',fx:'tactics'},{n:'戰鬥續行',r:'A',fx:'survive'}],
    traits:[{n:'王'},{n:'人類'}], np:'無數騎士之證・呼喚英雄之劍（對軍 B）',
    align:'中立・善', persona:{firstP:'余',words:'浪漫・崇拜英雄・天真豪邁',toMaster:'坦率信賴，視為冒險夥伴'} },
  { id:'阿基里斯-Rider', cls:'Rider', realName:'阿基里斯', wars:['fake'], gender:'男',
    six:{筋力:'A',耐久:'B',敏捷:'A+',魔力:'C',幸運:'B',寶具:'A'},
    classSkills:[{n:'騎乘',r:'A+',fx:'ride'},{n:'對魔力',r:'C',fx:'nullify_magic'}],
    skills:[{n:'神性',r:'C',fx:'divine'},{n:'勇猛',r:'A+',fx:'morale'},{n:'神威的車輪',r:'A',fx:'survive'}],
    traits:[{n:'神性'},{n:'英雄'}], np:'貫穿戰場的流星（對人 A）／守護領域的車輪（除踵無敵）',
    align:'混沌・中庸', persona:{firstP:'我',words:'戰士・自由奔放・驕傲重情',toMaster:'豪爽不羈，認可便傾力'} },
  { id:'大仲馬-Caster', cls:'Caster', realName:'亞歷山大·仲馬', wars:['fake'], gender:'男',
    six:{筋力:'E',耐久:'E',敏捷:'D',魔力:'D',幸運:'C',寶具:'C'},
    classSkills:[{n:'道具作成',r:'EX',fx:'crafting'},{n:'陣地作成',r:'C',fx:'territory'}],
    skills:[{n:'故事創作',r:'A',fx:'narrative'},{n:'心眼(真)',r:'B',fx:'analyze'},{n:'怪力（妙筆生兵）',r:'C',fx:'str_up'}],
    traits:[{n:'人類'}], np:'文豪的妙筆・鍛造英靈的兵裝（道具作成 EX）',
    align:'混沌・善', persona:{firstP:'我',words:'文豪・健談・市儈卻浪漫',toMaster:'毒舌愛吐槽，實則照拂'} },
  { id:'開膛手傑克-Berserker', cls:'Berserker', realName:'開膛手傑克', wars:['fake'], gender:'女',
    six:{筋力:'C',耐久:'C',敏捷:'A',魔力:'B',幸運:'D',寶具:'B'},
    classSkills:[{n:'狂化',r:'C',fx:'mad'},{n:'氣息遮斷',r:'B',fx:'stealth'}],
    skills:[{n:'霧夜的殺戮',r:'B',fx:'zabaniya'},{n:'變化（散為霧）',r:'C',fx:'shapeshift'},{n:'情報抹消',r:'A',fx:'unreadable'}],
    traits:[{n:'人類'}], np:'霧夜的殺戮 The Mist（對人・心臟摘除）',
    align:'混沌・惡', persona:{firstP:'我們',words:'孩童・空虛・渴求母愛・殘忍',toMaster:'試探地索求溫柔'} },
  { id:'靜謐的哈桑-Assassin', cls:'Assassin', realName:'靜謐的哈桑', wars:['fake'], gender:'女',
    six:{筋力:'D',耐久:'D',敏捷:'A',魔力:'C',幸運:'C',寶具:'C'},
    classSkills:[{n:'氣息遮斷',r:'A+',fx:'stealth'}],
    skills:[{n:'自我改造（毒身）',r:'B',fx:'self_mod'},{n:'妄想心音',r:'B',fx:'zabaniya'},{n:'透化',r:'C',fx:'clear_mind'}],
    traits:[{n:'人類'}], np:'妄想心音・幻影瞬心 Zabaniya（心臟一擊）',
    align:'秩序・惡', persona:{firstP:'我',words:'孤獨・自我毒身・溫柔的殺意',toMaster:'寡言順從，珍視被需要'} },
  { id:'伊絲塔-Archer', cls:'Archer', realName:'伊絲塔', wars:['fake'], gender:'女',
    six:{筋力:'B',耐久:'C',敏捷:'B',魔力:'A',幸運:'B',寶具:'A+'},
    classSkills:[{n:'對魔力',r:'C',fx:'nullify_magic'},{n:'單獨行動',r:'A',fx:'solo'}],
    skills:[{n:'神性',r:'A',fx:'divine'},{n:'女神的神核',r:'A',fx:'divine_core'},{n:'魔力放出',r:'A',fx:'burst'}],
    traits:[{n:'神性'},{n:'女神'}], np:'天之公牛・山海熔毀的天牛（對界 A+）',
    align:'混沌・善', persona:{firstP:'本小姐',words:'女神・任性・傲嬌・愛美',toMaster:'頤指氣使，意外講義氣'} },
  // 客串英靈
  { id:'莫德雷德-Saber', cls:'Saber', realName:'莫德雷德', wars:['客串'], gender:'女',
    six:{筋力:'B',耐久:'B',敏捷:'B',魔力:'C',幸運:'C',寶具:'A'},
    classSkills:[{n:'對魔力',r:'B',fx:'nullify_magic'},{n:'騎乘',r:'B',fx:'ride'}],
    skills:[{n:'直感',r:'B',fx:'first_strike'},{n:'魔力放出',r:'A',fx:'burst'},{n:'卡里斯瑪',r:'C',fx:'morale'}],
    traits:[{n:'龍'},{n:'騎士'}], np:'我的憤怒不會退去 Clarent Blood Arthur（對軍 A）',
    align:'混沌・中庸', persona:{firstP:'我',words:'叛逆・倔強・渴求認同',toMaster:'桀驁不馴，認可便死忠'} },
  { id:'卡爾納-Lancer', cls:'Lancer', realName:'卡爾納', wars:['客串'], gender:'男',
    six:{筋力:'A',耐久:'B',敏捷:'A',魔力:'B',幸運:'C',寶具:'A+'},
    classSkills:[{n:'對魔力',r:'C',fx:'nullify_magic'},{n:'騎乘',r:'A',fx:'ride'}],
    skills:[{n:'神性',r:'B',fx:'divine'},{n:'魔力放出（炎）',r:'A',fx:'burst'},{n:'太陽之鎧',r:'A',fx:'divine_core'}],
    traits:[{n:'神性'},{n:'英雄'}], np:'日輪啊化作鎧甲吧／梵天慈悲之槍（對神 EX）',
    align:'秩序・善', persona:{firstP:'我',words:'施與者・寡言・高潔',toMaster:'沉默守諾，恩怨分明'} },
  { id:'阿斯托爾福-Rider', cls:'Rider', realName:'阿斯托爾福', wars:['客串'], gender:'男',
    six:{筋力:'D',耐久:'C',敏捷:'B',魔力:'C',幸運:'A',寶具:'C'},
    classSkills:[{n:'騎乘',r:'A+',fx:'ride'},{n:'對魔力',r:'C',fx:'nullify_magic'}],
    skills:[{n:'直感',r:'A',fx:'first_strike'},{n:'怪力',r:'C',fx:'str_up'},{n:'純真無垢',r:'B',fx:'clear_mind'}],
    traits:[{n:'人類'},{n:'騎士'}], np:'觸發傳說的魔笛 La Black Luna／破卻 Casta Diva',
    align:'混沌・善', persona:{firstP:'我',words:'天真爛漫・無憂・忠誠',toMaster:'活力滿滿，全心信賴'} },
  { id:'賽彌拉米斯-Assassin', cls:'Assassin', realName:'賽彌拉米斯', wars:['客串'], gender:'女',
    six:{筋力:'D',耐久:'C',敏捷:'C',魔力:'B',幸運:'B',寶具:'A+'},
    classSkills:[{n:'氣息遮斷',r:'C',fx:'stealth'}],
    skills:[{n:'陣地作成（空中庭園）',r:'EX',fx:'territory'},{n:'道具作成（毒）',r:'A',fx:'crafting'},{n:'女神的神核',r:'',fx:'divine_core'}],
    traits:[{n:'神性'},{n:'人類'}], np:'虛榮的空中庭園（對軍・對界）',
    align:'混沌・惡', persona:{firstP:'妾',words:'毒后・傲慢・貞潔的執念',toMaster:'高高在上，唯認可強主'} },
  { id:'尼祿-Saber', cls:'Saber', realName:'尼祿·克勞狄烏斯', wars:['客串'], gender:'女',
    six:{筋力:'C',耐久:'C',敏捷:'B',魔力:'C',幸運:'B',寶具:'B'},
    classSkills:[{n:'對魔力',r:'C',fx:'nullify_magic'},{n:'騎乘',r:'C',fx:'ride'}],
    skills:[{n:'卡里斯瑪',r:'C',fx:'morale'},{n:'皇帝特權',r:'A',fx:'survive'},{n:'三度全否定',r:'-',fx:'clear_mind'}],
    traits:[{n:'王'},{n:'人類'}], np:'燃燒吧、世界的盡頭 Aestus Domus Aurea（對人・黃金劇場）',
    align:'混沌・善', persona:{firstP:'朕',words:'暴君・自戀・藝術・天真',toMaster:'熱情張揚，渴望被讚美'} },
  { id:'玉藻前-Caster', cls:'Caster', realName:'玉藻前', wars:['客串'], gender:'女',
    six:{筋力:'E',耐久:'D',敏捷:'C',魔力:'A',幸運:'A',寶具:'A'},
    classSkills:[{n:'陣地作成',r:'A',fx:'territory'},{n:'道具作成',r:'B',fx:'crafting'}],
    skills:[{n:'高速神言',r:'A',fx:'fast_cast'},{n:'變化',r:'A',fx:'shapeshift'},{n:'狐之治癒',r:'A',fx:'rune'}],
    traits:[{n:'神性'},{n:'野獸'}], np:'水天日光天照八野鎮（治癒結界）／八純之鎖',
    align:'混沌・中庸', persona:{firstP:'妾身',words:'賢妻・腹黑・愛吐槽',toMaster:'撒嬌又掌控，黏人'} },
  { id:'牛若丸-Rider', cls:'Rider', realName:'源義經（牛若丸）', wars:['客串'], gender:'女',
    six:{筋力:'D',耐久:'D',敏捷:'A',魔力:'D',幸運:'C',寶具:'C'},
    classSkills:[{n:'騎乘',r:'A',fx:'ride'},{n:'對魔力',r:'C',fx:'nullify_magic'}],
    skills:[{n:'神性',r:'D',fx:'divine'},{n:'天狗之兵法',r:'B',fx:'first_strike'},{n:'牛若之武略',r:'B',fx:'tactics'}],
    traits:[{n:'神性'},{n:'人類'}], np:'壇之浦・八艘飛（對人・神速跳躍）',
    align:'混沌・善', persona:{firstP:'牛若',words:'悲劇武者・純真・崇拜兄長',toMaster:'純粹追隨，赤誠'} },
  { id:'貞德-Ruler', cls:'Ruler', realName:'貞德', wars:['客串'], gender:'女',
    six:{筋力:'C',耐久:'B',敏捷:'B',魔力:'B',幸運:'A',寶具:'A'},
    classSkills:[{n:'對魔力',r:'A',fx:'nullify_magic'},{n:'真名看破',r:'A',fx:'analyze'}],
    skills:[{n:'啟示',r:'A',fx:'first_strike'},{n:'守護的旗幟',r:'B',fx:'survive'},{n:'領袖魅力',r:'B',fx:'morale'}],
    traits:[{n:'人類'}], np:'吾主在此 Luminosité Eternelle（守護結界）／紅蓮聖女 La Pucelle',
    align:'秩序・善', persona:{firstP:'我',words:'聖女・堅毅・溫柔的信念',toMaster:'溫柔守護，循循善誘'} },
  { id:'美遊-Saber', cls:'Saber', realName:'美遊·埃德費爾特（Saber install）', wars:['客串'], gender:'女',
    six:{筋力:'B',耐久:'B',敏捷:'B',魔力:'C',幸運:'C',寶具:'A'},
    classSkills:[{n:'對魔力',r:'B',fx:'nullify_magic'},{n:'騎乘',r:'B',fx:'ride'}],
    skills:[{n:'直感',r:'B',fx:'first_strike'},{n:'魔力放出',r:'B',fx:'burst'},{n:'沉著冷靜',r:'B',fx:'clear_mind'}],
    traits:[{n:'人類'},{n:'騎士'}], np:'約定勝利之劍 Excalibur（對城 A+）',
    align:'秩序・善', persona:{firstP:'我',words:'寡言・認真・溫柔內斂・背負宿命',toMaster:'認真盡責，沉默守護'} },
  { id:'小黑-Archer', cls:'Archer', realName:'克洛伊·馮·愛因茲貝倫（Archer install）', wars:['客串'], gender:'女',
    six:{筋力:'C',耐久:'C',敏捷:'A',魔力:'B',幸運:'C',寶具:'B'},
    classSkills:[{n:'對魔力',r:'D',fx:'nullify_magic'},{n:'單獨行動',r:'B',fx:'solo'}],
    skills:[{n:'投影魔術',r:'B',fx:'projection'},{n:'千里眼',r:'C',fx:'aim'},{n:'無限劍製',r:'C',fx:'ubw'}],
    traits:[{n:'人類'}], np:'無限劍製 Unlimited Blade Works／干將・莫邪（雙劍亂舞）',
    align:'混沌・中庸', persona:{firstP:'本小姐',words:'腹黑・愛捉弄・直率好戰・撒嬌',toMaster:'又黏又愛逗弄，戰意旺盛'} },
  { id:'伊莉雅-Caster', cls:'Caster', realName:'伊莉雅絲菲爾·馮·愛因茲貝倫（Caster install）', wars:['客串'], gender:'女',
    six:{筋力:'D',耐久:'C',敏捷:'C',魔力:'A',幸運:'B',寶具:'B'},
    classSkills:[{n:'陣地作成',r:'B',fx:'territory'},{n:'道具作成（魔杖・露比）',r:'C',fx:'crafting'}],
    skills:[{n:'高速神言',r:'A',fx:'fast_cast'},{n:'魔力放出',r:'B',fx:'burst'},{n:'純真無垢',r:'A',fx:'clear_mind'}],
    traits:[{n:'人類'}], np:'全彈發射・魔力炮 Quintett Feuer（多重魔力炮擊）',
    align:'中立・善', persona:{firstP:'我',words:'天真活潑・善良・愛哭卻勇敢',toMaster:'純真信賴，朝氣蓬勃'} }
];

var SEED_MASTERS = [
  // 第五次
  {id:'衛宮士郎-5th',  name:'衛宮士郎', gender:'男', appearance:'紅褐短髮的高中生，樸素襯衫',   war:'5th', magic:'投影／強化',          circuits:30, melee:'D', magic_rank:'D', home:'冬木·深山町', wish:'成為正義的伙伴',          persona:'理想主義・自我犧牲'},
  {id:'遠坂凜-5th',    name:'遠坂凜', gender:'女', appearance:'黑長雙馬尾、紅衣黑裙，傲然',     war:'5th', magic:'寶石魔術',            circuits:45, melee:'C', magic_rank:'A', home:'遠坂宅',     wish:'見證聖杯・不負遠坂之名',  persona:'高傲堅強・刀子嘴豆腐心'},
  {id:'間桐慎二-5th',  name:'間桐慎二', gender:'男', appearance:'藍髮神經質青年，刻薄表情',   war:'5th', magic:'魔術迴路微弱・依賴從者', circuits:15, melee:'E', magic_rank:'E', home:'間桐宅',     wish:'被認可・奪取勝利',        persona:'自卑虛榮・色厲內荏'},
  {id:'葛木宗一郎-5th',name:'葛木宗一郎', gender:'男', appearance:'戴眼鏡的沉默教師，黑西裝', war:'5th', magic:'體術（蛇之拳）・無魔術', circuits:10, melee:'A', magic_rank:'E', home:'柳洞寺',     wish:'無所求・守護 Caster',     persona:'冷靜寡言・絕對忠誠'},
  {id:'言峰綺禮-5th',  name:'言峰綺禮', gender:'男', appearance:'高大神父、黑色法衣，陰沉',   war:'5th', magic:'代行者・黑鍵',        circuits:25, melee:'A', magic_rank:'C', home:'言峰教會',   wish:'尋得能讓自己喜悅之物',    persona:'壓抑・扭曲的虔誠'},
  {id:'伊莉雅絲菲爾-5th',name:'伊莉雅絲菲爾', gender:'女', appearance:'紅眼白髮的幼小少女，毛領大衣',war:'5th',magic:'愛因茲貝倫煉金術・聖杯依代',    circuits:80, melee:'D', magic_rank:'A', home:'冬木·新都', wish:'完成聖杯的使命',          persona:'天真與哀傷並存'},
  {id:'間桐櫻(黑化)-5th',name:'間桐櫻（黑化）', gender:'女', appearance:'黑長髮、黑紅禮服，妖異而空洞的笑',war:'5th',magic:'聖杯之泥・無限魔力・蟲爪', circuits:90, melee:'E', magic_rank:'A', home:'間桐宅', wish:'獨佔所愛、將傷害自己的世界一同拖入黑暗', persona:'純愛扭曲為佔有・被黑泥吞噬'},
  // 第四次
  {id:'衛宮切嗣-4th',  name:'衛宮切嗣', gender:'男', appearance:'黑髮疲憊的男人，風衣',   war:'4th', magic:'起源彈・固有時制御',    circuits:35, melee:'A', magic_rank:'B', home:'冬木·深山町', wish:'以聖杯拯救世界、終結戰爭',persona:'冷酷務實・為大義不擇手段'},
  {id:'遠坂時臣-4th',  name:'遠坂時臣', gender:'男', appearance:'金棕髮的優雅紳士，名門做派',   war:'4th', magic:'寶石魔術',            circuits:50, melee:'D', magic_rank:'A', home:'遠坂宅',     wish:'抵達「根源之渦」',        persona:'優雅傲慢・名門做派'},
  {id:'肯尼斯-4th',    name:'肯尼斯', gender:'男', appearance:'金髮高傲的年輕教授',     war:'4th', magic:'礦石科・流體操作',      circuits:50, melee:'C', magic_rank:'A', home:'冬木·新都', wish:'榮譽與學術成就',          persona:'自尊極高・學究'},
  {id:'韋伯·維爾維特-4th',name:'韋伯·維爾維特', gender:'男', appearance:'黑髮瘦小的少年魔術師',war:'4th',magic:'自我暗示・基礎魔術', circuits:25, melee:'E', magic_rank:'C', home:'冬木·新都', wish:'證明自己的價值',          persona:'自卑好強・成長中'},
  {id:'雨生龍之介-4th',name:'雨生龍之介', gender:'男', appearance:'輕浮的金髮青年，咧嘴而笑', war:'4th', magic:'無魔術・召喚術（外行）', circuits:10, melee:'C', magic_rank:'E', home:'冬木·新都', wish:'見識更有趣的事物・召喚惡魔',persona:'開朗的瘋狂'},
  {id:'言峰綺禮-4th',  name:'言峰綺禮', gender:'男', appearance:'尚未墮落的青年神父，壓抑',   war:'4th', magic:'代行者・黑鍵',        circuits:25, melee:'A', magic_rank:'C', home:'言峰教會',   wish:'探求自身空虛的答案',      persona:'壓抑・尚未墮落'},
  {id:'間桐雁夜-4th',  name:'間桐雁夜', gender:'男', appearance:'蟲蝕半白頭髮的憔悴男子',   war:'4th', magic:'間桐之蟲術',          circuits:15, melee:'D', magic_rank:'C', home:'間桐宅',     wish:'從間桐手中救出櫻',        persona:'悲憤・自我犧牲'}
];

// 從者物件 → 英靈殿列（順序＝COL.HERO）
function servantToHeroRow_(s) {
  return [s.id, s.cls, s.realName, s.gender, JSON.stringify(s.six),
    JSON.stringify(s.classSkills), JSON.stringify(s.skills), JSON.stringify(s.traits),
    s.np, JSON.stringify(s.persona), s.align, JSON.stringify(s.wars), 'seed'];
}
// 御主物件 → 御主殿列（順序＝COL.MASTER）
function masterToCodexRow_(m) {
  return [m.id, m.name, m.gender, m.appearance, m.magic, m.circuits, m.melee,
    m.magic_rank, m.home, m.wish, m.persona, m.war, 'seed'];
}

// 🔵 英靈殿/御主殿 為空(只有表頭)時，自動灌入名冊。冪等：有資料就不動。
function seedFateCodex_(ss) {
  ss = ss || SpreadsheetApp.getActiveSpreadsheet();
  var hero = ss.getSheetByName('英靈殿');
  if (hero && hero.getLastRow() <= 1) {
    var hrows = SEED_SERVANTS.map(servantToHeroRow_);
    hero.getRange(2, 1, hrows.length, hrows[0].length).setValues(hrows);
  }
  var master = ss.getSheetByName('御主殿');
  if (master && master.getLastRow() <= 1) {
    var mrows = SEED_MASTERS.map(masterToCodexRow_);
    master.getRange(2, 1, mrows.length, mrows[0].length).setValues(mrows);
  }
}

// 可從編輯器手動執行
function seedFateCodex() {
  seedFateCodex_();
  return '英靈殿 ' + SEED_SERVANTS.length + ' 騎、御主殿 ' + SEED_MASTERS.length + ' 名（若原本為空才寫入）。';
}
